//
//  PLVPaymentResultAdditionalData.h
//  PaylevenSDK
//
//  Created by Alexei Kuznetsov on 04.12.14.
//  Copyright (c) 2014 payleven Holding GmbH. All rights reserved.
//

#import <Foundation/Foundation.h>

#import "PLVPaymentResult.h"


/** Payment result additional data. */
@interface PLVPaymentResultAdditionalData : NSObject

/** Truncated Primary Account Number (PAN) displaying the last four digits of the PAN. Possible characters: [0-9]. E.g. 1234 */
@property(nonatomic, readonly, copy) NSString *primaryAccountNumberLastDigits;
@property(nonatomic, readonly, copy) NSString *primaryAccountNumber DEPRECATED_MSG_ATTRIBUTE("use primaryAccountNumberLastDigits");

/**
 Masked Primary Account Number (PAN) that displays the last four digits of the card number used for the payment. Possible characters: 0-9, X. E.g. XXXXXXXXXXXX1234
 */
@property(nonatomic, readonly, copy) NSString *primaryAccountNumberMasked;

/** Maximum length of the untruncated primary account number for the card brand specified in cardBrandIdentifier. E.g. 16 */
@property(nonatomic, readonly, assign) NSUInteger maximumPrimaryAccountNumberMaskedLength;
@property(nonatomic, readonly, assign) NSUInteger maximumPrimaryAccountNumberLength DEPRECATED_MSG_ATTRIBUTE(" maximumPrimaryAccountNumberMaskedLength");

/** Primary account number sequence number. Identifies and differentiates cards with the same PAN. Possible characters: [0-9]. E.g. 01*/
@property(nonatomic, readonly, copy) NSString *primaryAccountNumberMaskedSequenceNumber;
@property(nonatomic, readonly, copy) NSString *primaryAccountNumberSequenceNumber DEPRECATED_MSG_ATTRIBUTE(" primaryAccountNumberMaskedSequenceNumber");

/** Indicates the method by which the Primary Account Number (PAN) was entered. */
@property(nonatomic, readonly, assign) PLVPointOfSaleEntryMode pointOfSaleEntryMode;

/** Verification method of the cardholder, used for the payment. */
@property(nonatomic, readonly, assign) PLVCardholderVerificationMethod cardholderVerificationMethod;

/** Identifies the application of the card used for the payment as described in ISO/IEC 7816-5. */
@property(nonatomic, readonly, copy) NSString *applicationIdentifier;

/** Authorization code generated by the issuing bank of a payer’s payment card, in order to validate a payment card when it is approved or declined in the sale of a good or service. */
@property(nonatomic, readonly, copy) NSString *authorizationCode;

/** Card brand identifier used for the payment. */
@property(nonatomic, readonly, copy) NSString *cardBrandIdentifier;

/** Card brand name used for the payment. */
@property(nonatomic, readonly, copy) NSString *cardBrandName;
/**
 * Expiration month of the card used for the payment. Returns 2 digits. Possible characters: [0-9].
 */
@property(nonatomic, readonly) NSInteger cardExpiryMonth;
@property(nonatomic, readonly) NSInteger expiryMonth DEPRECATED_MSG_ATTRIBUTE("use cardExpiryMonth");
/**
 * Expiration year of the card used for the payment.  Returns 4 digits. Possible characters: [0-9].
 */
@property(nonatomic, readonly) NSInteger cardExpiryYear;
@property(nonatomic, readonly) NSInteger expiryYear DEPRECATED_MSG_ATTRIBUTE("use cardExpiryMonth");;

@end
