//
//  PLVRefundRequest.h
//  PaylevenSDK
//
//  Created by Bob Obi on 7/22/15.
//  Copyright (c) 2015 payleven Holding GmbH. All rights reserved.
//

#import <Foundation/Foundation.h>
/**
  @brief PLVRefundRequest is used to create or generate the PLVRefundRequest for refunds.
  It implements a NSCopying protocol and the mandatory properties are made readonly.
  Contains a refundDescription property that can be set later or assigned before the
  start of the actual task PLVRefundTask.
 */
@interface PLVRefundRequest : NSObject<NSCopying>

/**
 * Refund Identifier.
 *
 Mandatory unique identifier of the refund request generated by the integrator on behalf of the merchant(s).
 The ID can be any set of alphanumeric characters [A-Z, a-z, 0-9].
 This refund identifier must be included in receipts and will be reflected on payleven's receipt images. Please retain this identifier for your records.
 */
@property(nonatomic, readonly, nonnull) NSString *refundIdentifier;
@property(nonatomic, readonly, nonnull) NSString *identifier DEPRECATED_MSG_ATTRIBUTE("use refundIdentifier");

/**
 * Payment Identifier.
 *
 Mandatory unique identifier (e.g order number) of a payment referring to the initial sale payment to be refunded.
 The ID can be any set of alphanumeric characters [A-Z, a-z, 0-9].
 This payment identifier must be included in receipts and will be reflected on payleven's receipt images. Please retain this identifier for your records and for further reference (e.g Refund).
 */
@property(nonatomic, readonly, nonnull) NSString *paymentIdentifier;

/**
 * Amount to be charged in a decimal format, which must be at least one major currency unit (e.g 1.00 Euro) and cannot be negative or zero.
 *
 * The value can be fractional, maximum two fraction digits are allowed.
 *
 * When creating `NSDecimalNumber` from `NSString`, don't forget to take the current locale and the decimal separator
 * into account.
 */
@property(nonatomic, readonly, nonnull) NSDecimalNumber *refundAmount;
@property(nonatomic, readonly, nonnull) NSDecimalNumber *amount DEPRECATED_MSG_ATTRIBUTE("use refundAmount");

/**
 * Three-letter alphabetic code according to ISO 4217 representing the refund's currency. Currency must not deviate from initial sale payment's currency. Supported currencies are EUR, GBP and PLN.
 */
@property(nonatomic, readonly, nonnull) NSString *refundCurrency;
@property(nonatomic, readonly, nonnull) NSString *currency DEPRECATED_MSG_ATTRIBUTE("use refundCurrency");

/**
 * Refund Description
 *
 * Optional description provided by the merchant (max 140 characters).
 */
@property(nonatomic, nullable) NSString *refundDescription;

/**
 * Initializer. With the specified identifier, paymentIdentifier, amount, currency and refundDescription
 * refundDescription could be nil and it is seen as optional in swift
 *
 * @param identifier Refund identifier.
 * @param paymentIdentifier identifier.
 * @param amount Payment amount. The value can be fractional, maximum two fraction digits are allowed. When creating
 *               `NSDecimalNumber` from `NSString`, don't forget to take the current locale and the decimal separator
 *               into account.
 * @param currency Three-letter ISO 4217 currency code. For example, EUR.
 * @param refundDescription a description that can be added by the client limited to 140 characters.
 */
- (nonnull instancetype)initWithIdentifier:(nonnull NSString *)identifier
                 paymentIdentifier:(nonnull NSString *)paymentIdentifier
                            amount:(nonnull NSDecimalNumber *)amount
                          currency:(nonnull NSString *)currency
                 refundDescription:(nullable NSString *)refundDescription NS_DESIGNATED_INITIALIZER;

@end

